### ISSUE TITLE
Proper parsing of mongo response is required in backend.

### ISSUE THREAD

**Issue by SiddhantJ19** [Vineet-Sharma29/citra#2]
The response from Mongo DB is directly being redirected to client. Proper error handling is required.

**Comment by SiddhantJ19** [comment]
Got this when trying to create a duplicate account.
 LOG  {"driver":true,"name":"MongoError","index":0,"code":11000,"errmsg":"E11000 duplicate key error collection: citra.residents index: email_1 dup key: { : \"siddhant.j17@iiits.in\" }"}

**Comment by deep-fried-potato** [comment]
error log is for development purposes. use the status code provided to determine the type of error.
